"""empty message

Revision ID: 155a38c05656
Revises: a889268b7181
Create Date: 2022-10-04 18:25:06.699458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155a38c05656'
down_revision = 'a889268b7181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('register', sa.Column('poster', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('register', 'poster')
    # ### end Alembic commands ###
