"""empty message

Revision ID: bc72132ac54e
Revises: 7b2d5b2ad816
Create Date: 2022-09-24 07:10:03.935535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc72132ac54e'
down_revision = '7b2d5b2ad816'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('register_show_key', 'register', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('register_show_key', 'register', ['show'])
    # ### end Alembic commands ###
